apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base

patches:
- path: patch-replicas.yaml

images:
- name: devsharvari/fastapi-app
  newName: devsharvari/fastapi-app
  newTag: 6a986f32deba77f3495447afe270cceb00b890bd
