apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base

patches:
- path: patch-replicas.yaml

images:
- name: devsharvari/fastapi-app
  newName: devsharvari/fastapi-app
  newTag: ae6c16db296d51381862a74662a392baf6f3ee2e
